services:
  mongo:
    image: mongo:7
    container_name: ai-interview-test-tool-mongo
    restart: unless-stopped
    environment:
      # Change these if you want different creds
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      # Optional: pre-create an app database
      MONGO_INITDB_DATABASE: ai_interview_test_tool
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet mongodb://root:example@localhost:27017/admin --eval 'db.runCommand({ ping: 1 })' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  minio:
    image: minio/minio:latest
    container_name: ai-interview-test-tool-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  mongo_data:
  minio_data:
